// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF53YoswZxjeoj-ZWPMt5ev-GSAKVj1uI',
    appId: '1:625297713861:web:f6eddafe3c80754e959eac',
    messagingSenderId: '625297713861',
    projectId: 'ethans-portfolio-552c1',
    authDomain: 'ethans-portfolio-552c1.firebaseapp.com',
    databaseURL: 'https://ethans-portfolio-552c1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ethans-portfolio-552c1.appspot.com',
    measurementId: 'G-0GZ46QEGDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2nEiFd8G9JyV3u-ea9nO_d2yNcn0HD9I',
    appId: '1:625297713861:android:e07d7d2978941d96959eac',
    messagingSenderId: '625297713861',
    projectId: 'ethans-portfolio-552c1',
    databaseURL: 'https://ethans-portfolio-552c1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ethans-portfolio-552c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefEiULUI59ZlgT0BeGFkWOclIa2SRPmg',
    appId: '1:625297713861:ios:7c202b79e648a6b4959eac',
    messagingSenderId: '625297713861',
    projectId: 'ethans-portfolio-552c1',
    databaseURL: 'https://ethans-portfolio-552c1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ethans-portfolio-552c1.appspot.com',
    iosClientId: '625297713861-kqj8vpma6eni0gs7tlnp0opbpjuu5cgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfoliowebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBefEiULUI59ZlgT0BeGFkWOclIa2SRPmg',
    appId: '1:625297713861:ios:7c202b79e648a6b4959eac',
    messagingSenderId: '625297713861',
    projectId: 'ethans-portfolio-552c1',
    databaseURL: 'https://ethans-portfolio-552c1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ethans-portfolio-552c1.appspot.com',
    iosClientId: '625297713861-kqj8vpma6eni0gs7tlnp0opbpjuu5cgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfoliowebsite',
  );
}
